# Generated by Django 4.2 on 2025-05-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250, verbose_name='Название брэнда')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, verbose_name='Название категории:')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=250, verbose_name='Название товара:')),
                ('descrip', models.TextField(verbose_name='Описание продукта:')),
                ('main_image', models.ImageField(upload_to='products/', verbose_name='Главное изображение:')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 3')),
                ('price', models.PositiveIntegerField(verbose_name='Цена продукта:')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Брэнд:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория:')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
